### ISSUE TITLE
iem-200w.csv is too big to save with excel online, could  you pls offer any other download link?

### ISSUE THREAD

**Issue by guessyin** [HongxinXiang/IEM#2]

**Comment by HongxinXiang** [comment]
When visiting the link provided, do not open it with excel online but directly click on the download button on the page.

**Comment by SmallHamster2020** [comment]
> When visiting the link provided, do not open it with excel online but directly click on the download button on the page.

I cant download iem-200w.csv either, every time i access the download link, it will switch to microsoft login page.Is there any other way?

**Comment by HongxinXiang** [comment]
I added a link to Baidu Netdisk, please try it. I think onedrive might be biased towards opening csv files.
