### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by yuhanchenzz** [HongxinXiang/IEM#3]
作者您好！十分感谢你们的开源！
我对你们的工作非常感兴趣，我尝试将你们提供的训练好的Teacher模型，应用于新的下游任务，但是我在提供的代码中，没有找到下游数据集相关2D、3D图片获取，以及geometric_data_processed.pt生成的代码，请问可以提供吗?
期待您的回复！

**Comment by HongxinXiang** [comment]
抱歉，回复晚了。感谢您对我们工作的兴趣，我们已经更新了数据预处理的代码，请访问 README 中 Processing Yourself Data
 部分。
